# Generated by Django 4.1.5 on 2023-02-01 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsExpensesMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('total', models.FloatField(db_column='total')),
                ('day', models.IntegerField(db_column='day')),
                ('month', models.IntegerField(db_column='month')),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'db_table': 'stats_expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=60)),
                ('additional_info', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
